import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

export interface GenerateTypesOptions {
  outputPath?: string | null;
  moduleName?: string;
  includeResource?: boolean;
  banner?: boolean;
}

export type FieldDefinition = string | ObjectFieldDefinition;

export interface ObjectFieldDefinition {
  type?: string;
  required?: boolean;
  description?: string;
  props?: Record<string, FieldDefinition>;
  items?: string | ObjectFieldDefinition;
  [key: string]: unknown;
}

export interface TypeGenResourceConfig {
  attributes?: Record<string, FieldDefinition>;
  timestamps?: boolean;
}

export interface TypeGenResource {
  config?: TypeGenResourceConfig;
  attributes?: Record<string, FieldDefinition>;
  schema?: { _pluginAttributes?: Record<string, string[]> };
}

export interface TypeGenDatabase {
  resources: Record<string, TypeGenResource>;
}

export interface ResourceInterface {
  name: string;
  interfaceName: string;
}

const typeMap: Record<string, string> = {
  string: 'string', text: 'string', secret: 'string', email: 'string', url: 'string',
  date: 'string', datetime: 'string', dateonly: 'string', timeonly: 'string', uuid: 'string',
  ip4: 'string', ip6: 'string', mac: 'string', cidr: 'string', phone: 'string', color: 'string',
  semver: 'string', cron: 'string', locale: 'string', currency: 'string', country: 'string',
  ean: 'string', duration: 'string', password: 'string',
  number: 'number', integer: 'number', money: 'number', crypto: 'number', decimal: 'number', bits: 'number',
  boolean: 'boolean', bool: 'boolean', buffer: 'Buffer', array: 'unknown[]',
  object: 'Record<string, unknown>', json: 'unknown',
};

export function mapFieldTypeToTypeScript(fieldType: string): string {
  const baseType = fieldType.split('|')[0]?.trim() || 'unknown';
  if (baseType.startsWith('embedding:')) return 'number[]';
  return typeMap[baseType] ?? 'unknown';
}

export function isFieldRequired(field: FieldDefinition): boolean {
  if (typeof field === 'string') return field.split('|').includes('required');
  return field.required === true || (typeof field.type === 'string' && field.type.split('|').includes('required'));
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value);
}

function pascalCase(value: string): string {
  const name = value.split(/[^A-Za-z0-9_$]+/).filter(Boolean)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('') || 'Resource';
  return /^[A-Za-z_$]/.test(name) ? name : `Resource${name}`;
}

function comment(value: string): string {
  return value.replace(/\*\//g, '* /').replace(/[\r\n]+/g, ' ');
}

function fieldType(field: FieldDefinition, indent = '  '): string {
  if (typeof field === 'string') return mapFieldTypeToTypeScript(field);
  const type = field.type?.split('|')[0] ?? 'unknown';
  if (type === 'object' && field.props) {
    const fields = Object.entries(field.props).map(([name, definition]) => {
      const optional = isFieldRequired(definition) ? '' : '?';
      return `${indent}  ${propertyName(name)}${optional}: ${fieldType(definition, `${indent}  `)};`;
    });
    return `{\n${fields.join('\n')}\n${indent}}`;
  }
  if (type === 'array' && field.items) return `Array<${fieldType(field.items, indent)}>`;
  return mapFieldTypeToTypeScript(field.type ?? 'unknown');
}

export function generateResourceInterface(
  resourceName: string,
  attributes: Record<string, FieldDefinition>,
  timestamps = false
): string {
  const lines = [`export interface ${pascalCase(resourceName)} {`];
  if (!Object.hasOwn(attributes, 'id')) lines.push('  /** Resource ID */', '  id: string;');

  for (const [name, field] of Object.entries(attributes)) {
    if (typeof field === 'object' && field.description) lines.push(`  /** ${comment(field.description)} */`);
    lines.push(`  ${propertyName(name)}${isFieldRequired(field) ? '' : '?'}: ${fieldType(field)};`);
  }
  if (timestamps && !Object.hasOwn(attributes, 'createdAt')) lines.push('  createdAt: string;');
  if (timestamps && !Object.hasOwn(attributes, 'updatedAt')) lines.push('  updatedAt: string;');
  lines.push('}', '');
  return lines.join('\n');
}

export async function generateTypes(database: TypeGenDatabase, options: GenerateTypesOptions = {}): Promise<string> {
  const {
    outputPath = './types/database.d.ts',
    moduleName = '@baldin/core',
    includeResource = true,
    banner = true,
  } = options;
  const lines: string[] = [];
  if (banner) lines.push('/** Auto-generated by @baldin/typegen. Do not edit. */', '');
  if (includeResource) {
    lines.push(`import type { Database, Resource } from ${JSON.stringify(moduleName)};`, '');
    lines.push('export type TypedResource<T> = Omit<Resource,',
      "  'get' | 'getOrNull' | 'getOrThrow' | 'insert' | 'update' | 'patch' | 'replace' | 'list' | 'query'",
      '> & {',
      '  get(id: string): Promise<T>;',
      '  getOrNull(id: string): Promise<T | null>;',
      '  getOrThrow(id: string): Promise<T>;',
      '  insert(data: Partial<T>): Promise<T>;',
      '  update(id: string, data: Partial<T>): Promise<T>;',
      '  patch(id: string, data: Partial<T>): Promise<T>;',
      '  replace(id: string, data: Partial<T>): Promise<T>;',
      '  list(options?: unknown): Promise<T[]>;',
      '  query(filters: Partial<T>, options?: unknown): Promise<T[]>;',
      '};', '');
  }

  const resources: ResourceInterface[] = [];
  for (const [name, resource] of Object.entries(database.resources)) {
    const attributes = resource.config?.attributes ?? resource.attributes ?? {};
    const pluginAttributes = new Set(Object.values(resource.schema?._pluginAttributes ?? {}).flat());
    const userAttributes = Object.fromEntries(Object.entries(attributes).filter(([field]) => !pluginAttributes.has(field)));
    lines.push(generateResourceInterface(name, userAttributes, resource.config?.timestamps ?? false));
    resources.push({ name, interfaceName: pascalCase(name) });
  }

  lines.push('export interface ResourceMap {');
  for (const resource of resources) {
    const valueType = includeResource ? `TypedResource<${resource.interfaceName}>` : 'unknown';
    lines.push(`  ${propertyName(resource.name)}: ${valueType};`);
  }
  lines.push('}', '');
  if (includeResource) lines.push("export type TypedDatabase = Omit<Database, 'resources'> & { resources: ResourceMap };", '');

  const content = lines.join('\n');
  if (outputPath) {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, content, 'utf8');
  }
  return content;
}

export function printTypes(database: TypeGenDatabase, options: GenerateTypesOptions = {}): Promise<string> {
  return generateTypes(database, { ...options, outputPath: null });
}

export default { generateTypes, printTypes };
